from trie import *
from linkedlist import *
        
T = Trie()

print("-_-_-_-_- TRIE CON LISTAS DE PYTHON -_-_-_-_- ")
print("=========== PRUEBA Insert una palabra =========== ")
insert(T, "zapatilla")
print(T.root[0].key)
print(T.root[0].children[0].key)
print(T.root[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].key)

insert(T, "zapatos")
print("")
print(T.root[0].key)
print(T.root[0].children[0].key)
print(T.root[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].key)
print(T.root[0].children[0].children[0].children[0].children[0].children[1].key)
print(T.root[0].children[0].children[0].children[0].children[0].children[1].children[0].key)

insert(T, "torta")
print("")
print(T.root[1].key)
print(T.root[1].children[0].key)
print(T.root[1].children[0].children[0].key)
print(T.root[1].children[0].children[0].children[0].key)
print(T.root[1].children[0].children[0].children[0].children[0].key)

insert(T, "tortita")
print("")
print(T.root[1].key)
print(T.root[1].children[0].key)
print(T.root[1].children[0].children[0].key)
print(T.root[1].children[0].children[0].children[0].key)
print(T.root[1].children[0].children[0].children[0].children[1].key)
print(T.root[1].children[0].children[0].children[0].children[1].children[0].key)
print(T.root[1].children[0].children[0].children[0].children[1].children[0].children[0].key)

print(search(T, "zapatos"))
print(search(T, "zapa"))
print(search(T, "vela"))
print(search(T, "tortita"))